### ISSUE TITLE
libaosd Installation Error

### ISSUE THREAD

**Issue by MathLens** [ztuowen/bilicom#2]
The program crashed in a few seconds after pressing shortcut key "n".
Version: 3.4.0
Error message:

```
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by ztuowen** [comment]
# This is the symptom of having an "invalid" installation of libaosd.

When having this error, you most likely **compiled it from source** either yourself or using some script that does the compilation (such as that from Archlinux's PKGBUILD).

## How do I know if mine is working?
- If it doesn't give the error as above :), JK
- If you could run `aosd_cat` in shell

## How do I fix it

### Check what is actually the problem
- Remember when you run `./configure --prefix=<somepath>`?
  - Is `<somepath>/bin` in your $PATH?
  - Is `<somepath>/lib` in your library path?
- Well it is in the path but how come it does not have aosd_cat in it?
  - Lack of certain libraries can still compile for libaosd
  - When you `./configure` there is a list at the end says `Configuration`
  - At least _glib-2.0_, _Pango-Cairo_ should be `yes`

## I got the source of libaosd how do I install
1. `./autogen.sh`
   - This would need `automake`
2. `./configure --prefix=<somepath>`
   - I prefer `<somepath>`=`/usr/local`
3. `make`
   - Check dependencies
4. `make install`
   - Use `sudo` if necessary

## Are there any scripts that I can use

**_There is none that I know of**_, but a good starting point would be [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libaosd-xinerama-git) from AUR

## This is just too complicated for me, and on screen notification isn't that big a deal anyway

Well, no problem. This program can run without on screen display.

Fixed: **_I've add a feature in 3.4.2 that should automatically disable on screen notification, in case of a buggy libaosd installation.**_
