### ISSUE TITLE
bilicom + OBS

### ISSUE THREAD

**Issue by emptymalei** [ztuowen/bilicom#3]
非常感谢这个 repo，非常好用。

想问个问题，这个有可能跟 obs 结合起来么？弹幕直接显示在 obs 的画面上？

**Comment by ztuowen** [comment]
本人也是做linux直播的，请问您所说的是“只”显示在直播流里还是显示在屏幕上就好了。
我一般是使用全屏的capture所以对于我来说显示在屏幕上就自动进入了直播流里。而且，如果只是窗口capture的话就看不见弹幕的说。

**Comment by emptymalei** [comment]
我原来想的是这样的：
![image](https://cloud.githubusercontent.com/assets/663798/15378679/ef90e11c-1d22-11e6-8806-132735774686.png)

不过现在想想，好像一点意义都没有，这样很不容易看到的。还是目前最好用。

我直播一直用这个的，感觉非常棒，特别是可以直接在命令行回复别人这个功能，简直最棒了。
